name: Front-end GitHub actions workflow for the resume challenge
 
# The workflow should only trigger on push events to the main branch
on:
  push:
    branches:
      - main
env:
  # Setting an environment variable with the value of a configuration variable
  env_region: ${{ vars.REGION }}

# Required to get the ID Token that will be used for OIDC
permissions:
  id-token: write
 
jobs:
  deploy-test:    
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.REGION }}
          role-to-assume: ${{ secrets.TEST_DEPLOY_ROLE }}
          role-session-name: OIDCSession
 
      - run: aws s3 sync ./static_site_files/static-website/ ${{ secrets.S3_BUCKET }}
        shell: bash